
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ANALIZADOR;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int doo = 10;
  public static final int igualigual = 21;
  public static final int falsee = 40;
  public static final int switchh = 11;
  public static final int consolelog = 44;
  public static final int llaveabierta = 16;
  public static final int coma = 35;
  public static final int igual = 20;
  public static final int classs = 2;
  public static final int parder = 19;
  public static final int requiree = 15;
  public static final int elsee = 7;
  public static final int puntoycoma = 31;
  public static final int casee = 12;
  public static final int menos = 32;
  public static final int menor = 25;
  public static final int truee = 39;
  public static final int iff = 6;
  public static final int constt = 5;
  public static final int EOF = 0;
  public static final int mas = 33;
  public static final int whilee = 9;
  public static final int error = 1;
  public static final int mayor = 24;
  public static final int lett = 4;
  public static final int breakk = 14;
  public static final int or = 23;
  public static final int menorigual = 30;
  public static final int por = 34;
  public static final int forr = 8;
  public static final int defaultt = 13;
  public static final int dospuntos = 38;
  public static final int id = 43;
  public static final int potencia = 37;
  public static final int llavecerrada = 17;
  public static final int mayorigual = 29;
  public static final int cadenas = 41;
  public static final int diferente = 27;
  public static final int varr = 3;
  public static final int and = 22;
  public static final int not = 28;
  public static final int parizq = 18;
  public static final int division = 36;
  public static final int decimal = 42;
  public static final int modulo = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "classs",
  "varr",
  "lett",
  "constt",
  "iff",
  "elsee",
  "forr",
  "whilee",
  "doo",
  "switchh",
  "casee",
  "defaultt",
  "breakk",
  "requiree",
  "llaveabierta",
  "llavecerrada",
  "parizq",
  "parder",
  "igual",
  "igualigual",
  "and",
  "or",
  "mayor",
  "menor",
  "modulo",
  "diferente",
  "not",
  "mayorigual",
  "menorigual",
  "puntoycoma",
  "menos",
  "mas",
  "por",
  "coma",
  "division",
  "potencia",
  "dospuntos",
  "truee",
  "falsee",
  "cadenas",
  "decimal",
  "id",
  "consolelog"
  };
}

