/* The following code was generated by JFlex 1.7.0 */

package ANALIZADOR2;
import java_cup.runtime.Symbol; 


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/ANALIZADOR2/lexer.jflex</tt>
 */
public class LEXER1 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\10\1\10\1\10\1\10\22\0\1\6\1\0\1\11"+
    "\1\7\1\14\3\0\1\44\1\45\1\12\1\0\1\40\1\0\1\4"+
    "\1\13\12\3\1\41\1\43\1\0\1\42\3\0\1\22\1\51\1\33"+
    "\1\50\1\24\1\36\1\25\1\56\1\35\1\23\1\2\1\27\1\52"+
    "\1\20\1\37\1\16\1\2\1\26\1\32\1\21\1\17\1\54\1\2"+
    "\1\53\1\55\1\2\1\46\1\0\1\47\1\0\1\2\1\0\1\22"+
    "\1\51\1\33\1\50\1\24\1\36\1\25\1\56\1\35\1\23\1\2"+
    "\1\27\1\52\1\20\1\37\1\16\1\2\1\26\1\32\1\21\1\17"+
    "\1\54\1\2\1\53\1\55\1\2\1\15\1\5\1\30\7\0\1\10"+
    "\32\0\1\1\217\0\2\34\115\0\1\31\u1500\0\1\1\u097f\0\13\1"+
    "\35\0\1\10\1\10\5\0\1\1\57\0\1\1\u0fa0\0\1\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\3\1\1\5\4\3"+
    "\1\6\1\1\2\3\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\2\3\1\0\1\2\2\0\1\17"+
    "\2\0\5\3\1\0\5\3\1\4\4\0\5\3\1\0"+
    "\5\3\4\0\2\3\1\20\2\3\1\0\2\3\1\0"+
    "\3\3\1\2\2\0\1\3\1\0\2\3\1\0\1\3"+
    "\1\0\2\3\1\0\3\3\1\0\2\21\1\0\2\3"+
    "\1\0\1\3\2\22\1\3\1\0\1\3\1\23\1\3"+
    "\1\0\1\24\1\25\1\24\1\25\2\26\1\3\1\0"+
    "\1\3\1\27\1\0\1\3\2\30\1\0\1\3\3\0"+
    "\3\3\1\0\1\3\1\0\1\3\3\0\3\3\1\0"+
    "\1\3\2\0\1\3\1\31\2\0\1\31\2\3\1\0"+
    "\1\3\2\0\1\3\2\0\2\3\1\0\1\3\2\0"+
    "\1\3\2\0\2\3\1\0\1\3\2\0\1\3\1\32"+
    "\1\33\1\32\1\33\1\0\1\3\2\0\1\3\1\0"+
    "\1\3\2\0\1\3\2\34\3\0\1\3\1\0\1\35"+
    "\1\0\1\3\2\0\1\3\2\0\1\3\2\0\1\3"+
    "\2\0\1\3\2\0\1\3\2\0\1\3\2\0\1\3"+
    "\1\0\2\36\3\0\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\57\0\u0178\0\u01a7\0\u01d6\0\u0205\0\57\0\u0234\0\u0263"+
    "\0\u0292\0\136\0\57\0\57\0\57\0\57\0\57\0\57"+
    "\0\57\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u011a\0\57"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u031f\0\u060f\0\u063e"+
    "\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\215\0\u09ea\0\u0a19\0\u0a48\0\u0a77"+
    "\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\57\0\u0b91\0\u0bc0"+
    "\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\57\0\215\0\u0fca"+
    "\0\u0ff9\0\u1028\0\215\0\u1057\0\u1086\0\57\0\57\0\215"+
    "\0\215\0\57\0\215\0\u10b5\0\u10e4\0\u1113\0\215\0\u1142"+
    "\0\u1171\0\57\0\215\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c"+
    "\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4"+
    "\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d\0\u154c"+
    "\0\u157b\0\u15aa\0\57\0\u15d9\0\u1608\0\215\0\u1637\0\u1666"+
    "\0\u1695\0\u16c4\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af\0\u17de"+
    "\0\u180d\0\u183c\0\u186b\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956"+
    "\0\u1985\0\u19b4\0\u19e3\0\u1a12\0\u1a41\0\u1a70\0\u1a9f\0\57"+
    "\0\57\0\215\0\215\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b\0\u1b8a"+
    "\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u1c75\0\57\0\215\0\u1ca4"+
    "\0\u1cd3\0\u1d02\0\u1d31\0\u1d60\0\57\0\u1d8f\0\u1dbe\0\u1ded"+
    "\0\u1e1c\0\u1e4b\0\u1e7a\0\u1ea9\0\u1ed8\0\u1f07\0\u1f36\0\u1f65"+
    "\0\u1f94\0\u1fc3\0\u1ff2\0\u2021\0\u2050\0\u207f\0\u20ae\0\u20dd"+
    "\0\u210c\0\u213b\0\u216a\0\u2199\0\u21c8\0\57\0\215\0\u21f7"+
    "\0\u2226\0\u2255\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\2\1\3\1\6\1\3"+
    "\1\7\2\2\1\10\1\11\3\4\1\12\1\13\1\4"+
    "\1\14\1\15\2\4\1\16\1\17\1\20\1\21\1\2"+
    "\3\4\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\3\4\1\33\2\4\60\0\1\3\4\0"+
    "\1\3\1\0\1\3\27\0\1\3\20\0\2\4\12\0"+
    "\12\4\2\0\2\4\1\0\3\4\10\0\7\4\3\0"+
    "\1\5\1\34\61\0\1\35\2\0\1\36\44\0\11\37"+
    "\1\40\45\37\15\0\1\41\43\0\2\4\12\0\12\4"+
    "\2\0\2\4\1\42\1\43\2\4\10\0\7\4\2\0"+
    "\2\4\12\0\10\4\1\44\1\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\5\4\1\45"+
    "\4\4\2\0\2\4\1\0\3\4\10\0\7\4\2\0"+
    "\2\4\12\0\6\4\1\46\1\4\1\47\1\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\21\0\1\50\37\0"+
    "\2\4\12\0\3\4\1\51\6\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\12\4\2\0"+
    "\2\4\1\0\2\4\1\52\10\0\7\4\2\0\2\4"+
    "\12\0\6\4\1\53\3\4\2\0\2\4\1\0\2\4"+
    "\1\54\10\0\7\4\2\0\2\4\12\0\4\4\1\55"+
    "\5\4\2\0\2\4\1\0\3\4\10\0\7\4\3\0"+
    "\1\56\1\0\2\56\50\0\10\35\1\0\46\35\13\57"+
    "\1\60\43\57\16\0\1\61\61\0\1\62\37\0\2\4"+
    "\12\0\3\4\1\63\6\4\2\0\2\4\1\0\3\4"+
    "\10\0\7\4\2\0\2\4\12\0\12\4\2\0\1\4"+
    "\1\64\1\0\3\4\10\0\7\4\2\0\2\4\12\0"+
    "\6\4\1\65\3\4\2\0\2\4\1\0\3\4\10\0"+
    "\7\4\2\0\2\4\12\0\2\4\1\66\7\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\2\0\2\4\12\0"+
    "\4\4\1\67\5\4\2\0\2\4\1\0\3\4\10\0"+
    "\7\4\26\0\1\70\32\0\2\4\12\0\10\4\1\71"+
    "\1\4\2\0\2\4\1\0\3\4\10\0\7\4\2\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\3\4\10\0"+
    "\2\4\1\72\4\4\2\0\2\4\12\0\12\4\2\0"+
    "\2\4\1\0\1\4\1\73\1\4\10\0\7\4\2\0"+
    "\2\4\12\0\1\4\1\74\10\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\11\4\1\75"+
    "\2\0\2\4\1\0\3\4\10\0\7\4\12\57\1\76"+
    "\44\57\12\0\1\77\1\60\62\0\1\100\56\0\1\101"+
    "\41\0\2\4\12\0\1\4\1\102\10\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\2\0\2\4\12\0\12\4"+
    "\2\0\2\4\1\0\3\4\10\0\6\4\1\103\2\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\3\4\10\0"+
    "\3\4\1\104\3\4\2\0\2\4\12\0\6\4\1\105"+
    "\3\4\2\0\2\4\1\0\3\4\10\0\7\4\2\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\1\4\1\106"+
    "\1\4\10\0\7\4\34\0\2\107\23\0\2\4\12\0"+
    "\12\4\2\0\2\4\1\107\1\110\2\4\10\0\7\4"+
    "\2\0\2\4\12\0\1\111\11\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\12\4\2\0"+
    "\2\4\1\112\1\113\2\4\10\0\7\4\2\0\2\4"+
    "\12\0\12\4\2\0\2\4\1\0\3\4\10\0\1\4"+
    "\1\114\5\4\2\0\2\4\12\0\12\4\2\0\2\4"+
    "\1\0\2\4\1\115\10\0\7\4\7\57\1\116\2\57"+
    "\1\76\44\57\7\0\1\116\67\0\1\117\65\0\1\120"+
    "\31\0\2\4\12\0\11\4\1\121\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\12\4\2\0"+
    "\2\4\1\122\1\123\2\4\10\0\7\4\2\0\2\4"+
    "\12\0\10\4\1\124\1\4\2\0\2\4\1\0\3\4"+
    "\10\0\7\4\2\0\2\4\12\0\12\4\2\0\2\4"+
    "\1\125\1\126\2\4\10\0\7\4\20\0\1\127\40\0"+
    "\2\4\12\0\2\4\1\130\7\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\4\4\1\131"+
    "\5\4\2\0\2\4\1\0\3\4\10\0\7\4\20\0"+
    "\1\132\40\0\2\4\12\0\2\4\1\133\7\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\2\0\2\4\12\0"+
    "\11\4\1\134\2\0\2\4\1\0\3\4\10\0\7\4"+
    "\2\0\2\4\12\0\10\4\1\135\1\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\21\0\1\136\74\0\1\137"+
    "\21\0\2\4\12\0\12\4\2\0\2\4\1\0\2\4"+
    "\1\140\10\0\7\4\54\0\1\141\4\0\2\4\12\0"+
    "\12\4\2\0\2\4\1\0\3\4\10\0\4\4\1\142"+
    "\2\4\2\0\2\4\12\0\4\4\1\143\5\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\33\0\1\144\25\0"+
    "\2\4\12\0\12\4\2\0\1\4\1\145\1\0\3\4"+
    "\10\0\7\4\25\0\1\146\33\0\2\4\12\0\7\4"+
    "\1\147\2\4\2\0\2\4\1\0\3\4\10\0\7\4"+
    "\2\0\2\4\12\0\10\4\1\150\1\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\34\0\2\151\23\0\2\4"+
    "\12\0\12\4\2\0\2\4\1\151\1\152\2\4\10\0"+
    "\7\4\2\0\2\4\12\0\6\4\1\153\3\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\2\0\2\4\12\0"+
    "\6\4\1\154\3\4\2\0\2\4\1\0\3\4\10\0"+
    "\7\4\22\0\1\155\107\0\1\156\1\0\1\157\3\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\3\4\10\0"+
    "\3\4\1\160\1\4\1\161\1\4\37\0\1\162\21\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\2\4\1\163"+
    "\10\0\7\4\2\0\2\4\12\0\10\4\1\164\1\4"+
    "\2\0\2\4\1\0\3\4\10\0\7\4\22\0\1\165"+
    "\36\0\2\4\12\0\4\4\1\166\5\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\2\0\2\4\12\0\6\4"+
    "\1\167\3\4\2\0\2\4\1\0\3\4\10\0\7\4"+
    "\26\0\1\170\32\0\2\4\12\0\10\4\1\171\1\4"+
    "\2\0\2\4\1\0\3\4\10\0\7\4\2\0\2\4"+
    "\12\0\12\4\1\0\1\172\1\173\1\4\1\0\3\4"+
    "\10\0\7\4\23\0\1\174\35\0\2\4\12\0\10\4"+
    "\1\175\1\4\2\0\2\4\1\0\3\4\10\0\7\4"+
    "\16\0\1\176\10\0\1\177\21\0\1\200\7\0\2\4"+
    "\12\0\1\201\10\4\1\202\2\0\2\4\1\0\3\4"+
    "\10\0\1\4\1\203\5\4\25\0\1\204\33\0\2\4"+
    "\12\0\7\4\1\205\2\4\2\0\2\4\1\0\3\4"+
    "\10\0\7\4\24\0\1\206\34\0\2\4\12\0\6\4"+
    "\1\207\3\4\2\0\2\4\1\0\3\4\10\0\7\4"+
    "\34\0\2\210\55\0\2\211\43\0\1\212\36\0\2\4"+
    "\12\0\12\4\2\0\2\4\1\210\1\213\2\4\10\0"+
    "\7\4\2\0\2\4\12\0\12\4\2\0\2\4\1\211"+
    "\1\214\2\4\10\0\7\4\2\0\2\4\12\0\4\4"+
    "\1\215\5\4\2\0\2\4\1\0\3\4\10\0\7\4"+
    "\27\0\1\216\31\0\2\4\12\0\11\4\1\217\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\24\0\1\220\1\221"+
    "\33\0\2\4\12\0\1\222\11\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\24\0\1\223\52\0\1\224\64\0"+
    "\1\225\32\0\2\4\12\0\6\4\1\226\3\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\2\0\2\4\12\0"+
    "\2\4\1\227\7\4\2\0\2\4\1\0\3\4\10\0"+
    "\7\4\2\0\2\4\12\0\10\4\1\230\1\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\37\0\1\231\21\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\2\4\1\232"+
    "\10\0\7\4\31\0\2\233\50\0\1\234\34\0\2\4"+
    "\12\0\12\4\2\0\2\4\1\0\2\4\1\235\10\0"+
    "\7\4\24\0\1\236\60\0\1\237\32\0\2\4\12\0"+
    "\6\4\1\240\3\4\2\0\2\4\1\0\3\4\10\0"+
    "\7\4\2\0\2\4\12\0\10\4\1\241\1\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\51\0\1\242\7\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\0\3\4\10\0"+
    "\1\4\1\243\5\4\16\0\1\244\60\0\1\245\40\0"+
    "\2\4\12\0\10\4\1\246\1\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\22\0\1\247\56\0\1\250\36\0"+
    "\2\4\12\0\4\4\1\251\5\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\2\0\2\4\12\0\4\4\1\252"+
    "\5\4\2\0\2\4\1\0\3\4\10\0\7\4\22\0"+
    "\1\253\36\0\2\4\12\0\4\4\1\254\5\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\24\0\1\255\56\0"+
    "\1\256\34\0\2\4\12\0\3\4\1\257\6\4\2\0"+
    "\2\4\1\0\3\4\10\0\7\4\31\0\2\260\55\0"+
    "\2\261\26\0\2\4\12\0\12\4\1\0\1\260\1\262"+
    "\1\4\1\0\3\4\10\0\7\4\2\0\2\4\12\0"+
    "\12\4\1\0\1\261\1\263\1\4\1\0\3\4\10\0"+
    "\7\4\27\0\1\264\31\0\2\4\12\0\11\4\1\265"+
    "\2\0\2\4\1\0\3\4\10\0\7\4\33\0\1\266"+
    "\51\0\1\267\32\0\2\4\12\0\6\4\1\270\3\4"+
    "\2\0\2\4\1\0\3\4\10\0\7\4\24\0\1\271"+
    "\34\0\2\4\12\0\6\4\1\272\3\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\34\0\2\273\43\0\1\274"+
    "\36\0\2\4\12\0\6\4\1\275\3\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\31\0\2\276\26\0\2\4"+
    "\12\0\12\4\1\0\1\276\1\277\1\4\1\0\3\4"+
    "\10\0\7\4\36\0\1\300\47\0\1\301\31\0\2\4"+
    "\12\0\12\4\1\0\1\302\1\303\1\4\1\0\3\4"+
    "\10\0\7\4\34\0\2\304\51\0\1\305\47\0\1\306"+
    "\37\0\2\4\12\0\3\4\1\307\6\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\33\0\1\310\45\0\1\311"+
    "\36\0\2\4\12\0\4\4\1\312\5\4\2\0\2\4"+
    "\1\0\3\4\10\0\7\4\37\0\1\313\67\0\1\314"+
    "\10\0\2\4\12\0\12\4\2\0\2\4\1\0\3\4"+
    "\10\0\1\315\6\4\40\0\1\316\52\0\2\317\23\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\317\1\320\2\4"+
    "\10\0\7\4\11\0\1\321\76\0\2\322\26\0\2\4"+
    "\12\0\12\4\1\0\1\322\1\323\1\4\1\0\3\4"+
    "\10\0\7\4\11\321\1\324\45\321\21\0\1\325\37\0"+
    "\2\4\12\0\3\4\1\326\6\4\2\0\2\4\1\0"+
    "\3\4\10\0\7\4\40\0\1\327\52\0\2\330\23\0"+
    "\2\4\12\0\12\4\2\0\2\4\1\330\1\331\2\4"+
    "\10\0\7\4\11\0\1\332\100\0\1\333\25\0\2\4"+
    "\12\0\12\4\2\0\1\4\1\334\1\0\3\4\10\0"+
    "\7\4\11\332\1\335\45\332\37\0\1\336\21\0\2\4"+
    "\12\0\12\4\2\0\2\4\1\0\2\4\1\337\10\0"+
    "\7\4\40\0\1\340\27\0\1\341\45\0\11\341\1\342"+
    "\45\341\30\0\1\343\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8836];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\4\1\1\11\4\1\7\11"+
    "\2\1\1\0\1\1\2\0\1\11\2\0\5\1\1\0"+
    "\6\1\4\0\5\1\1\0\5\1\4\0\5\1\1\0"+
    "\2\1\1\0\3\1\1\11\2\0\1\1\1\0\2\1"+
    "\1\0\1\1\1\0\2\1\1\0\3\1\1\0\2\1"+
    "\1\0\2\1\1\0\1\1\1\11\2\1\1\0\3\1"+
    "\1\0\2\11\2\1\1\11\2\1\1\0\2\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\3\0\3\1\1\0"+
    "\1\1\1\0\1\1\3\0\3\1\1\0\1\1\2\0"+
    "\1\1\1\11\2\0\3\1\1\0\1\1\2\0\1\1"+
    "\2\0\2\1\1\0\1\1\2\0\1\1\2\0\2\1"+
    "\1\0\1\1\2\0\1\1\2\11\2\1\1\0\1\1"+
    "\2\0\1\1\1\0\1\1\2\0\1\1\1\11\1\1"+
    "\3\0\1\1\1\0\1\11\1\0\1\1\2\0\1\1"+
    "\2\0\1\1\2\0\1\1\2\0\1\1\2\0\1\1"+
    "\2\0\1\1\2\0\1\1\1\0\1\11\1\1\3\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LEXER1(java.io.Reader in) {
      yyline = 1; 
    yychar = 1; 
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 252) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Este es un error lexico: "+yytext()+", en la linea: "+yyline+", en la columna: "+yychar);
            } 
            // fall through
          case 32: break;
          case 2: 
            { 
            } 
            // fall through
          case 33: break;
          case 3: 
            { return new Symbol (sym.id ,yyline,yychar,yytext());
            } 
            // fall through
          case 34: break;
          case 4: 
            { return new Symbol(sym.decimal,yyline,yychar, yytext());
            } 
            // fall through
          case 35: break;
          case 5: 
            { return new Symbol(sym.llaveabierta,yyline,yychar, yytext());
            } 
            // fall through
          case 36: break;
          case 6: 
            { return new Symbol(sym.llavecerrada,yyline,yychar, yytext());
            } 
            // fall through
          case 37: break;
          case 7: 
            { return new Symbol(sym.coma,yyline,yychar, yytext());
            } 
            // fall through
          case 38: break;
          case 8: 
            { return new Symbol(sym.dospuntos,yyline,yychar, yytext());
            } 
            // fall through
          case 39: break;
          case 9: 
            { return new Symbol(sym.igual,yyline,yychar, yytext());
            } 
            // fall through
          case 40: break;
          case 10: 
            { return new Symbol(sym.ptcoma,yyline,yychar, yytext());
            } 
            // fall through
          case 41: break;
          case 11: 
            { return new Symbol(sym.parizq,yyline,yychar, yytext());
            } 
            // fall through
          case 42: break;
          case 12: 
            { return new Symbol(sym.parder,yyline,yychar, yytext());
            } 
            // fall through
          case 43: break;
          case 13: 
            { return new Symbol(sym.corcheteabierto,yyline,yychar, yytext());
            } 
            // fall through
          case 44: break;
          case 14: 
            { return new Symbol(sym.corchetecerrado,yyline,yychar, yytext());
            } 
            // fall through
          case 45: break;
          case 15: 
            { return new Symbol (sym.cadenastring ,yyline,yychar,yytext());
            } 
            // fall through
          case 46: break;
          case 16: 
            { return new Symbol(sym.ejex,yyline,yychar, yytext());
            } 
            // fall through
          case 47: break;
          case 17: 
            { return new Symbol(sym.titulo,yyline,yychar, yytext());
            } 
            // fall through
          case 48: break;
          case 18: 
            { return new Symbol(sym.string,yyline,yychar, yytext());
            } 
            // fall through
          case 49: break;
          case 19: 
            { return new Symbol(sym.doublee,yyline,yychar, yytext());
            } 
            // fall through
          case 50: break;
          case 20: 
            { return new Symbol(sym.titulox,yyline,yychar, yytext());
            } 
            // fall through
          case 51: break;
          case 21: 
            { return new Symbol(sym.tituloy,yyline,yychar, yytext());
            } 
            // fall through
          case 52: break;
          case 22: 
            { return new Symbol(sym.archivo,yyline,yychar, yytext());
            } 
            // fall through
          case 53: break;
          case 23: 
            { return new Symbol(sym.compare,yyline,yychar, yytext());
            } 
            // fall through
          case 54: break;
          case 24: 
            { return new Symbol(sym.valores,yyline,yychar, yytext());
            } 
            // fall through
          case 55: break;
          case 25: 
            { return new Symbol(sym.graficapie,yyline,yychar, yytext());
            } 
            // fall through
          case 56: break;
          case 26: 
            { return new Symbol(sym.graficalienas,yyline,yychar, yytext());
            } 
            // fall through
          case 57: break;
          case 27: 
            { return new Symbol(sym.graficabarras,yyline,yychar, yytext());
            } 
            // fall through
          case 58: break;
          case 28: 
            { return new Symbol(sym.definirglobales,yyline,yychar, yytext());
            } 
            // fall through
          case 59: break;
          case 29: 
            { return new Symbol(sym.pgen,yyline,yychar, yytext());
            } 
            // fall through
          case 60: break;
          case 30: 
            { return new Symbol(sym.generarreporteestadistico,yyline,yychar, yytext());
            } 
            // fall through
          case 61: break;
          case 31: 
            { return new Symbol(sym.pesp,yyline,yychar, yytext());
            } 
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
