
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ANALIZADOR2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int string = 26;
  public static final int decimal = 21;
  public static final int llaveabierta = 8;
  public static final int coma = 25;
  public static final int archivo = 5;
  public static final int pesp = 30;
  public static final int tituloy = 18;
  public static final int titulox = 17;
  public static final int graficabarras = 13;
  public static final int doublee = 27;
  public static final int cadenastring = 23;
  public static final int titulo = 14;
  public static final int graficalienas = 20;
  public static final int ptcoma = 2;
  public static final int ejex = 15;
  public static final int corcheteabierto = 6;
  public static final int llavecerrada = 9;
  public static final int igual = 28;
  public static final int EOF = 0;
  public static final int id = 22;
  public static final int pgen = 29;
  public static final int error = 1;
  public static final int definirglobales = 10;
  public static final int graficapie = 19;
  public static final int parizq = 3;
  public static final int parder = 4;
  public static final int valores = 16;
  public static final int corchetecerrado = 7;
  public static final int dospuntos = 24;
  public static final int generarreporteestadistico = 11;
  public static final int compare = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ptcoma",
  "parizq",
  "parder",
  "archivo",
  "corcheteabierto",
  "corchetecerrado",
  "llaveabierta",
  "llavecerrada",
  "definirglobales",
  "generarreporteestadistico",
  "compare",
  "graficabarras",
  "titulo",
  "ejex",
  "valores",
  "titulox",
  "tituloy",
  "graficapie",
  "graficalienas",
  "decimal",
  "id",
  "cadenastring",
  "dospuntos",
  "coma",
  "string",
  "doublee",
  "igual",
  "pgen",
  "pesp"
  };
}

